### ISSUE TITLE
sslverify => false causes issues for me (maybe only locally??)

### ISSUE THREAD

**Issue by jtsternberg** [tw2113/WP-Contributions#2]
Result of the [wp_remote_get](https://github.com/WebDevStudios/WP-Contributions/blob/master/inc/class-wds-wp-contributions-core.php#L28)

```
WP_Error Object
(
    [errors] => Array
        (
            [http_request_failed] => Array
                (
                    [0] => SSL: CA certificate set, but certificate verification is disabled
                )

        )

    [error_data] => Array
        (
        )

)
```

**Comment by jtsternberg** [comment]
This is only an issue locally. Not sure why.

**Comment by colorful-tones** [comment]
Looks like this was a [known issue](http://stackoverflow.com/questions/26461966/osx-10-10-curl-post-to-https-url-gives-sslread-error/26538127#26538127) in Yosemite when PHP was compiled with a certain version of cURL. Wondering if this is still an issue for you @jtsternberg ?

Also, would love your insight on the expectation for providing a fix, and whether it would be a personal expectation of your's as a user and/or as a fellow plugin developer.
